server:
  port: 8888

spring:
  application:
    name: configservice
  cloud:
    config:
      server:
        git:
          uri: git@github.com:GC-AdvancedWebPrograming-WebGPT/config-repo.git
          ignoreLocalSshSettings: true
          default-label: main
          private-key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIKAl0J7y6hN4CU+drLtnOVLkS3oZ5ULFkBx3i6QhX+/VoAoGCCqGSM49
            AwEHoUQDQgAEM9NaL9jm3bOdBhkFP3tRJLfr9X74sKbXzpH7Wj2+WPDuwst8Sb+/
            +v1Jj4vV4HAF/To6y3UYpiao7qEKbFs/CQ==
            -----END EC PRIVATE KEY-----
          host-key: AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
          hostKeyAlgorithm: ecdsa-sha2-nistp256
          strict-host-key-checking: false
          timeout: 4

        encrypt:
          enabled: false

encrypt:
  key: key-brian

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true